### ISSUE TITLE
Compile failure

### ISSUE THREAD

**Issue by hvr** [cspollard/variation#1]
From the looks of it, this looks like the most recent `container` versions added an instance which `variation` defined as an orphan:

```
Configuring library for variation-0.1.0.0..
Preprocessing library for variation-0.1.0.0..
Building library for variation-0.1.0.0..
[1 of 3] Compiling Data.Monoid1     ( src/Data/Monoid1.hs, /tmp/matrix-worker/1497094846/dist-newstyle/build/x86_64-linux/ghc-8.2.0.20170522/variation-0.1.0.0/build/Data/Monoid1.o )
[2 of 3] Compiling Data.Variation.Instances ( src/Data/Variation/Instances.hs, /tmp/matrix-worker/1497094846/dist-newstyle/build/x86_64-linux/ghc-8.2.0.20170522/variation-0.1.0.0/build/Data/Variation/Instances.o )

src/Data/Variation/Instances.hs:9:10: error:
    Duplicate instance declarations:
      instance Show2 M.Map
        -- Defined at src/Data/Variation/Instances.hs:9:10
      instance Show2 M.Map -- Defined in ‘Data.Map.Internal’
  |
9 | instance Show2 M.Map where
  |          ^^^^^^^^^^^

src/Data/Variation/Instances.hs:16:10: error:
    Duplicate instance declarations:
      instance Show k => Show1 (M.Map k)
        -- Defined at src/Data/Variation/Instances.hs:16:10
      instance Show k => Show1 (M.Map k)
        -- Defined in ‘Data.Map.Internal’
   |
16 | instance Show k => Show1 (M.Map k) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^
<<ghc: 382686592 bytes, 119 GCs, 14478583/40539968 avg/max bytes residency (8 samples), 107M in use, 0.001 INIT (0.001 elapsed), 0.296 MUT (0.338 elapsed), 0.391 GC (0.393 elapsed) :ghc>>

```

**Comment by cspollard** [comment]
Could you show me an example of how to have instances that depend on package versions? Unfortunately the latest version of containers on stack does not define these, so I need to define them by hand.

**Comment by hvr** [comment]
@cspollard I've investigated a bit more, and the instances got added in 0.5.9...
(I've revised the meta-data at https://hackage.haskell.org/package/variation-0.1.0.0/revisions/ to reflect that)

Here's how to define them conditionally for containers < 0.5.9:

```hs
{-# LANGUAGE CPP #-}

-- ...

#if !MIN_VERSION_containers(0,5,9)
instance ...
#endif
```

However, do you *really* need those orphan instances? Since `variation` is a library, such instances should rather be defined in some canonical "orphan"-companion package (c.f. `base-orphans`), as otherwise due to the nature of orphan instances, it may become necessary for Hackage Trustees to retroactively overeagerly blacklist packages providing orphans, as there's no other way to avoid build-failures otherwise.

**Comment by cspollard** [comment]
Hi @hvr. Thanks very much for your feedback: never done this before. I've uploaded a new version to hackage (variation-0.1.1.0) that does not export orphan instances and also drops ghc 7.10 support for the time being. Does this look better?

Chris

**Comment by hvr** [comment]
@cspollard Looks good to me! ..and btw, if you have any questions regarding Hackage, Cabal or the [PVP](http://pvp.haskell.org), please don't hesitate to ask!

btw, see also https://matrix.hackage.haskell.org/package/variation

**Comment by cspollard** [comment]
@hvr very cool thanks. Will let you know if I have more Qs.
